Vet clinic database: create animals table
Debas-31/vet_clinic pull request #1
Opened 2022-03-21 20:25 UTC by Debas-31

##  Vet clinic database: create animals table
>In this milestone of the project added :  
- Create a table
- Insert data into the table
- Select queries from the database that I created.

2022-03-21 21:01 UTC, julie-ify requested changes
## Hi @Debas-31,

Good job so far!

## Highlights!
- Good feature branch name ✔️ 
- Descriptive pull request ✔️ 

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@julie-ify` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-21 21:01 UTC, julie-ify commented on queries.sql
> +SELECT * FROM animals WHERE name Not like 'Gabumon';
- [ ] Nice one so far. However, I suggest using a better query like `SELECT * FROM animals WHERE name <> 'Gabumon';` or `SELECT * FROM animals WHERE NOT name = 'Gabumon';` on line 9

2022-03-21 21:01 UTC, julie-ify commented on queries.sql
> +SELECT date_of_birth FROM animals WHERE name LIKE 'Agumon' OR name Like 'Pikachu';
- [ ] Kindly query this data well by replacing the query you have with this `SELECT date_of_birth FROM animals WHERE name = 'Pikachu' OR name = 'Agumon';` on line 6. Please read about the `LIKE` operator [here](https://www.w3schools.com/sql/sql_like.asp) so you will understand when to use it.

2022-03-21 21:01 UTC, julie-ify commented on queries.sql
> +SELECT name FROM animals WHERE date_of_birth BETWEEN '2016-01-01' AND '2019-01-01';
- [ ] This query should list the name of all animals born between `2016` and `2019`. However, your query is listing all animals born between the first day of January 2016 and the first day of January 2019 instead of the last day of December 2019. Kindly change your query to something like this; `SELECT name FROM animals WHERE date_of_birth >= '2016-01-01' AND date_of_birth <= '2019-31-12';`.

2022-03-21 21:01 UTC, julie-ify commented on queries.sql
> +SELECT * FROM animals WHERE name LIKE '%mon%';
- [ ] This query should be `SELECT * FROM animals WHERE name LIKE '%mon';` instead of `SELECT * FROM animals WHERE name LIKE '%mon%';`

2022-03-21 21:01 UTC, julie-ify commented on data.sql
> +INSERT INTO animals (name, date_of_birth, escape_attempts, neutered,weight_kg) VALUES('Devimon', '2017-05-12',5, True, 11);
- [ ] Kindly write your boolean value for `true` correctly. You're writing `True` instead of `true` or `TRUE`. I suggest writing it in lowercase `true` to match with your `false` value, which is written in lowercase.

2022-03-22 07:08 UTC, peterrobert commented on queries.sql
> +SELECT * FROM animals WHERE name Not like 'Gabumon';
This change has been implemented well

2022-03-22 07:10 UTC, peterrobert commented on queries.sql
> +SELECT date_of_birth FROM animals WHERE name LIKE 'Agumon' OR name Like 'Pikachu';
This change has been done well

2022-03-22 07:11 UTC, peterrobert commented on queries.sql
> +SELECT name FROM animals WHERE date_of_birth BETWEEN '2016-01-01' AND '2019-01-01';
This change has been done well

2022-03-22 07:11 UTC, peterrobert commented on queries.sql
> +SELECT * FROM animals WHERE name LIKE '%mon%';
This change has been done well

2022-03-22 07:12 UTC, peterrobert commented on data.sql
> +INSERT INTO animals (name, date_of_birth, escape_attempts, neutered,weight_kg) VALUES('Devimon', '2017-05-12',5, True, 11);
This change has been done well

2022-03-22 07:12 UTC, peterrobert approved these changes
Hi @Debas-31, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-22 07:45 UTC, merged