Query multiple tables
Debas-31/vet_clinic pull request #3
Opened 2022-03-23 21:36 UTC by Debas-31

## Vet Clinic: Query multiple tables
>In this project of the milestone implemented:
- [x] Added some new tables 
- [x] Added foreign key columns to existing animals table 
- [x] used JOIN to query the data.

2022-03-23 21:56 UTC, DammyShittu requested changes
Hi @Debas-31, 👋 

You have done an amazing job so far. 

Well done 👍 

There are little issues that you still need to work on to go to the next project but you are almost there!

# Required Changes ♻️

_Check the comments under the review._


# Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-23 21:56 UTC, DammyShittu commented on queries.sql
> +    GROUP BY full_name;
- Great queries so far. 👍 However, the last query says; `Who owns the most animals?`.
After running your query, this 👇 is what I got;

![](https://i.imgur.com/Eq3heew.png)

To get the person who owns the most animals, I believe the query should be written this 👇 way;

```
SELECT full_name, COUNT(name) FROM owners O
LEFT JOIN animals A
ON O.id = A.owner_id   GROUP BY full_name 
ORDER BY COUNT(name) 
DESC LIMIT 1;
```
😉

2022-03-23 21:56 UTC, DammyShittu commented on data.sql
> +WHERE name NOT LIKE '%mon';
- Kindly note that animals with names ending with `mon` are expected to belong to the `Digimon` species. According to the arrangement on lines 25 and 26, kindly alter the `species_id` on lines 29 and 33 to the right `id`. 😁

2022-03-24 07:48 UTC, AshakaE approved these changes
Hi @Debas-31 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-24 08:32 UTC, merged